### ISSUE TITLE
Differences between previous package

### ISSUE THREAD

**Issue by scrawlerapp** [dogokit/dogokit-remix#1]
Hello, I am using the codes on the previous github page and while reading the documentation, I saw that this page is now up to date. Since I developed my project in the previous package, I have a question I want to ask.

- Are there any bugs compared to the previous package? Have they been fixed in the new package?
- Is there a performance difference?
- Was the update made only as an interface?

I couldn't follow because there were too many commits.

**Comment by mhaidarhanif** [comment]
Hi @scrawlerapp 

- Which package to be specific? This repo is just a template so there's no package.
- Upgrading to Remix v2 has some performance benefits over Remix v1, but haven't measure them exactly.
- Usually only the interface, UI and UX.

No need to worry, if you want to start over, focus on the latest update of this repo. As it's just a template.
