### ISSUE TITLE
Prisma with MongoDB

### ISSUE THREAD

**Issue by jamesholcomb** [dogokit/dogokit-remix#2]
Hi, since you're using Prisma, do you foresee any issues (other than the tweaks necessary for the schema) to support mongodb?

P..S. I tried to open discussion for this, but it appears that is not enabled yet.

**Comment by mhaidarhanif** [comment]
Hi @jamesholcomb 

I haven't got time to check, try, or use MongoDB anymore. But you can try if Prisma support for it is stable enough.

There might be no significant changes to the Sshema. Only need to adapt what's possible or not between MySQL/PostgreSQL and MongoDB.

And currently I only recommend to use RDBMS like MySQL or PostgreSQL only, not document database like MongoDB.

Also this template is focusing on using MySQL and even guiding to use PlanetScale on production.

Recently just enabled Discussions: https://github.com/dogokit/dogokit-remix/discussions
