### ISSUE TITLE
Initial DB Seed Failed

### ISSUE THREAD

**Issue by esafirm** [dogokit/dogokit-remix#5]
# Bug report

## Describe the bug

The initial seeding process failed because of missing record

## To Reproduce

1. Clone the repo
1. Create the DB and do push `pnpm db:push`
2. Execute the seeding process `pnpm db:seed`

## Expected behavior

Seed was successful

## Screenshots

![CleanShot 2024-01-31 at 12 34 18@2x](https://github.com/dogokit/dogokit-remix/assets/1691440/d07f7780-2e76-4665-993a-2bf3f2c6d75c)

## Additional context

This is due to missing connected data in the seeding process. In [this line](https://github.com/dogokit/dogokit-remix/blob/main/prisma/seed.ts#L20), only `users` is enabled and there's nothing in the documentation that mention this.

**Comment by mhaidarhanif** [comment]
Already fixed by enabling all seed items in `seed.ts`
