### ISSUE TITLE
Better Error Message in User Seed Process

### ISSUE THREAD

**Issue by esafirm** [dogokit/dogokit-remix#6]
# Feature request

## Is the feature request related to a problem? Please describe

This request is related to a problem in the initial DB seeding process. 

If the user missed creating the `prisma/credentials/users.ts` file, ti will throw 

```
SyntaxError: The requested module './credentials/users' does not provide an export named 'dataCredentialUsers'
```

Instead of the error message that provided [in here](https://github.com/dogokit/dogokit-remix/blob/main/prisma/seed.ts#L110C3-L114C4)

```typescript
 if (!Array.isArray(dataCredentialUsers)) {
    console.error(`🔴 [ERROR] Please create prisma/credentials/users.ts file`)
    console.error(`🔴 [ERROR] Check README for the guide`)
    return null
  }
```
## Describe the solution

Create the file with an empty array instead, and check if the array is empty or not. Then apply git ignore so there's no future update on that file.

## Describe alternatives considered

A better way to detect the undeclared file maybe?

**Comment by mhaidarhanif** [comment]
@esafirm Thanks for the suggestion. In the meantime, developers or contributors are expected to check the README carefully.

**Comment by mhaidarhanif** [comment]
Currently developing the new version, Dogokit Akita: https://github.com/dogokit/dogokit-akita

Therefore this Dogokit repo, renamed as Dogokit Beagle, is being archived. So this issue is closed.
